spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: appuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate   # Flyway gestisce lo schema
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
server:
  port: 8080
